export const BANCHE_NOMI: string[] = [
  "ADV FINANCE S.P.A.", "AGOS", "ALTRA BANCA", "AVVERA",
  "BANCA CENTRO EMILIA SPA", "BANCA DI BOLOGNA", "BANCA ETICA",
  "BANCA GENERALI", "BANCA POPOLARE PUGLIESE", "BANCA PROGETTO",
  "BANCA SELLA", "BANCA SISTEMA", "BANCO DESIO", "BCC", "BCP",
  "BIBANCA", "BNL", "BNT", "BPER Banca", "BPM", "CAPITALFIN",
  "COFIDIS", "COMPASS", "CREDITIS", "DEUTSCHE BANK S.P.A.",
  "DYNAMICA RETAIL", "FIDES", "FIDITALIA", "FIGENPA S.P.A.",
  "FINCONTINUO", "FINDOMESTIC", "FINECO", "FINGENPA", "FUCINO",
  "IBL BANCA", "ING DIRECT", "INTESA SAN PAOLO", "ITALCREDI",
  "MEDIOLANUM", "MPS", "PITAGORA", "PRESTITALIA", "PREXTA",
  "SANTANDER", "SIGLA CREDIT", "SPEFIN", "TIM FIN", "UNICREDIT",
  "VIVIBANCA", "YOUNITED",
];