/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrattativeRouteImport } from './routes/_authenticated/trattative'
import { Route as AuthenticatedStatisticheRouteImport } from './routes/_authenticated/statistiche'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedRinnoviRouteImport } from './routes/_authenticated/rinnovi'
import { Route as AuthenticatedRequisitiAgenteRouteImport } from './routes/_authenticated/requisiti-agente'
import { Route as AuthenticatedProdottiRouteImport } from './routes/_authenticated/prodotti'
import { Route as AuthenticatedPrivatiRouteImport } from './routes/_authenticated/privati'
import { Route as AuthenticatedPreventiviSalvatiRouteImport } from './routes/_authenticated/preventivi-salvati'
import { Route as AuthenticatedPreventiviPrestitiRouteImport } from './routes/_authenticated/preventivi-prestiti'
import { Route as AuthenticatedPreventiviCessioniRouteImport } from './routes/_authenticated/preventivi-cessioni'
import { Route as AuthenticatedPratichePerseRouteImport } from './routes/_authenticated/pratiche-perse'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedMetaAdsRouteImport } from './routes/_authenticated/meta-ads'
import { Route as AuthenticatedMagazzinoRouteImport } from './routes/_authenticated/magazzino'
import { Route as AuthenticatedLogRegistroRouteImport } from './routes/_authenticated/log-registro'
import { Route as AuthenticatedLiquidatoRouteImport } from './routes/_authenticated/liquidato'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedGestionePraticheRouteImport } from './routes/_authenticated/gestione-pratiche'
import { Route as AuthenticatedFormContattiRouteImport } from './routes/_authenticated/form-contatti'
import { Route as AuthenticatedFatturazioneRouteImport } from './routes/_authenticated/fatturazione'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversazioniRouteImport } from './routes/_authenticated/conversazioni'
import { Route as AuthenticatedContenutiRouteImport } from './routes/_authenticated/contenuti'
import { Route as AuthenticatedContattiRouteImport } from './routes/_authenticated/contatti'
import { Route as AuthenticatedCalendariRouteImport } from './routes/_authenticated/calendari'
import { Route as AuthenticatedBlacklistRouteImport } from './routes/_authenticated/blacklist'
import { Route as AuthenticatedBancheRouteImport } from './routes/_authenticated/banche'
import { Route as AuthenticatedAziendeRouteImport } from './routes/_authenticated/aziende'
import { Route as AuthenticatedAutomazioneRouteImport } from './routes/_authenticated/automazione'
import { Route as AuthenticatedAttivitaRouteImport } from './routes/_authenticated/attivita'
import { Route as AuthenticatedAssicurazioniRouteImport } from './routes/_authenticated/assicurazioni'
import { Route as AuthenticatedLeadIndexRouteImport } from './routes/_authenticated/lead.index'
import { Route as AuthenticatedClientiIndexRouteImport } from './routes/_authenticated/clienti.index'
import { Route as AuthenticatedPreventiviSalvatiIdRouteImport } from './routes/_authenticated/preventivi-salvati_.$id'
import { Route as AuthenticatedLeadIdRouteImport } from './routes/_authenticated/lead.$id'
import { Route as AuthenticatedClientiIdRouteImport } from './routes/_authenticated/clienti.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrattativeRoute = AuthenticatedTrattativeRouteImport.update({
  id: '/trattative',
  path: '/trattative',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticheRoute =
  AuthenticatedStatisticheRouteImport.update({
    id: '/statistiche',
    path: '/statistiche',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRinnoviRoute = AuthenticatedRinnoviRouteImport.update({
  id: '/rinnovi',
  path: '/rinnovi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequisitiAgenteRoute =
  AuthenticatedRequisitiAgenteRouteImport.update({
    id: '/requisiti-agente',
    path: '/requisiti-agente',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProdottiRoute = AuthenticatedProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivatiRoute = AuthenticatedPrivatiRouteImport.update({
  id: '/privati',
  path: '/privati',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreventiviSalvatiRoute =
  AuthenticatedPreventiviSalvatiRouteImport.update({
    id: '/preventivi-salvati',
    path: '/preventivi-salvati',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreventiviPrestitiRoute =
  AuthenticatedPreventiviPrestitiRouteImport.update({
    id: '/preventivi-prestiti',
    path: '/preventivi-prestiti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreventiviCessioniRoute =
  AuthenticatedPreventiviCessioniRouteImport.update({
    id: '/preventivi-cessioni',
    path: '/preventivi-cessioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPratichePerseRoute =
  AuthenticatedPratichePerseRouteImport.update({
    id: '/pratiche-perse',
    path: '/pratiche-perse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetaAdsRoute = AuthenticatedMetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMagazzinoRoute = AuthenticatedMagazzinoRouteImport.update({
  id: '/magazzino',
  path: '/magazzino',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogRegistroRoute =
  AuthenticatedLogRegistroRouteImport.update({
    id: '/log-registro',
    path: '/log-registro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLiquidatoRoute = AuthenticatedLiquidatoRouteImport.update({
  id: '/liquidato',
  path: '/liquidato',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestionePraticheRoute =
  AuthenticatedGestionePraticheRouteImport.update({
    id: '/gestione-pratiche',
    path: '/gestione-pratiche',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormContattiRoute =
  AuthenticatedFormContattiRouteImport.update({
    id: '/form-contatti',
    path: '/form-contatti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFatturazioneRoute =
  AuthenticatedFatturazioneRouteImport.update({
    id: '/fatturazione',
    path: '/fatturazione',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversazioniRoute =
  AuthenticatedConversazioniRouteImport.update({
    id: '/conversazioni',
    path: '/conversazioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContenutiRoute = AuthenticatedContenutiRouteImport.update({
  id: '/contenuti',
  path: '/contenuti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContattiRoute = AuthenticatedContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendariRoute = AuthenticatedCalendariRouteImport.update({
  id: '/calendari',
  path: '/calendari',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlacklistRoute = AuthenticatedBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBancheRoute = AuthenticatedBancheRouteImport.update({
  id: '/banche',
  path: '/banche',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAziendeRoute = AuthenticatedAziendeRouteImport.update({
  id: '/aziende',
  path: '/aziende',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomazioneRoute =
  AuthenticatedAutomazioneRouteImport.update({
    id: '/automazione',
    path: '/automazione',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttivitaRoute = AuthenticatedAttivitaRouteImport.update({
  id: '/attivita',
  path: '/attivita',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssicurazioniRoute =
  AuthenticatedAssicurazioniRouteImport.update({
    id: '/assicurazioni',
    path: '/assicurazioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadIndexRoute = AuthenticatedLeadIndexRouteImport.update({
  id: '/lead/',
  path: '/lead/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientiIndexRoute =
  AuthenticatedClientiIndexRouteImport.update({
    id: '/clienti/',
    path: '/clienti/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreventiviSalvatiIdRoute =
  AuthenticatedPreventiviSalvatiIdRouteImport.update({
    id: '/preventivi-salvati_/$id',
    path: '/preventivi-salvati/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadIdRoute = AuthenticatedLeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientiIdRoute = AuthenticatedClientiIdRouteImport.update({
  id: '/clienti/$id',
  path: '/clienti/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/assicurazioni': typeof AuthenticatedAssicurazioniRoute
  '/attivita': typeof AuthenticatedAttivitaRoute
  '/automazione': typeof AuthenticatedAutomazioneRoute
  '/aziende': typeof AuthenticatedAziendeRoute
  '/banche': typeof AuthenticatedBancheRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/calendari': typeof AuthenticatedCalendariRoute
  '/contatti': typeof AuthenticatedContattiRoute
  '/contenuti': typeof AuthenticatedContenutiRoute
  '/conversazioni': typeof AuthenticatedConversazioniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatturazione': typeof AuthenticatedFatturazioneRoute
  '/form-contatti': typeof AuthenticatedFormContattiRoute
  '/gestione-pratiche': typeof AuthenticatedGestionePraticheRoute
  '/import': typeof AuthenticatedImportRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/liquidato': typeof AuthenticatedLiquidatoRoute
  '/log-registro': typeof AuthenticatedLogRegistroRoute
  '/magazzino': typeof AuthenticatedMagazzinoRoute
  '/meta-ads': typeof AuthenticatedMetaAdsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/pratiche-perse': typeof AuthenticatedPratichePerseRoute
  '/preventivi-cessioni': typeof AuthenticatedPreventiviCessioniRoute
  '/preventivi-prestiti': typeof AuthenticatedPreventiviPrestitiRoute
  '/preventivi-salvati': typeof AuthenticatedPreventiviSalvatiRoute
  '/privati': typeof AuthenticatedPrivatiRoute
  '/prodotti': typeof AuthenticatedProdottiRoute
  '/requisiti-agente': typeof AuthenticatedRequisitiAgenteRoute
  '/rinnovi': typeof AuthenticatedRinnoviRoute
  '/social': typeof AuthenticatedSocialRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
  '/trattative': typeof AuthenticatedTrattativeRoute
  '/clienti/$id': typeof AuthenticatedClientiIdRoute
  '/lead/$id': typeof AuthenticatedLeadIdRoute
  '/preventivi-salvati/$id': typeof AuthenticatedPreventiviSalvatiIdRoute
  '/clienti/': typeof AuthenticatedClientiIndexRoute
  '/lead/': typeof AuthenticatedLeadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/assicurazioni': typeof AuthenticatedAssicurazioniRoute
  '/attivita': typeof AuthenticatedAttivitaRoute
  '/automazione': typeof AuthenticatedAutomazioneRoute
  '/aziende': typeof AuthenticatedAziendeRoute
  '/banche': typeof AuthenticatedBancheRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/calendari': typeof AuthenticatedCalendariRoute
  '/contatti': typeof AuthenticatedContattiRoute
  '/contenuti': typeof AuthenticatedContenutiRoute
  '/conversazioni': typeof AuthenticatedConversazioniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatturazione': typeof AuthenticatedFatturazioneRoute
  '/form-contatti': typeof AuthenticatedFormContattiRoute
  '/gestione-pratiche': typeof AuthenticatedGestionePraticheRoute
  '/import': typeof AuthenticatedImportRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/liquidato': typeof AuthenticatedLiquidatoRoute
  '/log-registro': typeof AuthenticatedLogRegistroRoute
  '/magazzino': typeof AuthenticatedMagazzinoRoute
  '/meta-ads': typeof AuthenticatedMetaAdsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/pratiche-perse': typeof AuthenticatedPratichePerseRoute
  '/preventivi-cessioni': typeof AuthenticatedPreventiviCessioniRoute
  '/preventivi-prestiti': typeof AuthenticatedPreventiviPrestitiRoute
  '/preventivi-salvati': typeof AuthenticatedPreventiviSalvatiRoute
  '/privati': typeof AuthenticatedPrivatiRoute
  '/prodotti': typeof AuthenticatedProdottiRoute
  '/requisiti-agente': typeof AuthenticatedRequisitiAgenteRoute
  '/rinnovi': typeof AuthenticatedRinnoviRoute
  '/social': typeof AuthenticatedSocialRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
  '/trattative': typeof AuthenticatedTrattativeRoute
  '/clienti/$id': typeof AuthenticatedClientiIdRoute
  '/lead/$id': typeof AuthenticatedLeadIdRoute
  '/preventivi-salvati/$id': typeof AuthenticatedPreventiviSalvatiIdRoute
  '/clienti': typeof AuthenticatedClientiIndexRoute
  '/lead': typeof AuthenticatedLeadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/assicurazioni': typeof AuthenticatedAssicurazioniRoute
  '/_authenticated/attivita': typeof AuthenticatedAttivitaRoute
  '/_authenticated/automazione': typeof AuthenticatedAutomazioneRoute
  '/_authenticated/aziende': typeof AuthenticatedAziendeRoute
  '/_authenticated/banche': typeof AuthenticatedBancheRoute
  '/_authenticated/blacklist': typeof AuthenticatedBlacklistRoute
  '/_authenticated/calendari': typeof AuthenticatedCalendariRoute
  '/_authenticated/contatti': typeof AuthenticatedContattiRoute
  '/_authenticated/contenuti': typeof AuthenticatedContenutiRoute
  '/_authenticated/conversazioni': typeof AuthenticatedConversazioniRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fatturazione': typeof AuthenticatedFatturazioneRoute
  '/_authenticated/form-contatti': typeof AuthenticatedFormContattiRoute
  '/_authenticated/gestione-pratiche': typeof AuthenticatedGestionePraticheRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/liquidato': typeof AuthenticatedLiquidatoRoute
  '/_authenticated/log-registro': typeof AuthenticatedLogRegistroRoute
  '/_authenticated/magazzino': typeof AuthenticatedMagazzinoRoute
  '/_authenticated/meta-ads': typeof AuthenticatedMetaAdsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/pratiche-perse': typeof AuthenticatedPratichePerseRoute
  '/_authenticated/preventivi-cessioni': typeof AuthenticatedPreventiviCessioniRoute
  '/_authenticated/preventivi-prestiti': typeof AuthenticatedPreventiviPrestitiRoute
  '/_authenticated/preventivi-salvati': typeof AuthenticatedPreventiviSalvatiRoute
  '/_authenticated/privati': typeof AuthenticatedPrivatiRoute
  '/_authenticated/prodotti': typeof AuthenticatedProdottiRoute
  '/_authenticated/requisiti-agente': typeof AuthenticatedRequisitiAgenteRoute
  '/_authenticated/rinnovi': typeof AuthenticatedRinnoviRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/statistiche': typeof AuthenticatedStatisticheRoute
  '/_authenticated/trattative': typeof AuthenticatedTrattativeRoute
  '/_authenticated/clienti/$id': typeof AuthenticatedClientiIdRoute
  '/_authenticated/lead/$id': typeof AuthenticatedLeadIdRoute
  '/_authenticated/preventivi-salvati_/$id': typeof AuthenticatedPreventiviSalvatiIdRoute
  '/_authenticated/clienti/': typeof AuthenticatedClientiIndexRoute
  '/_authenticated/lead/': typeof AuthenticatedLeadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/assicurazioni'
    | '/attivita'
    | '/automazione'
    | '/aziende'
    | '/banche'
    | '/blacklist'
    | '/calendari'
    | '/contatti'
    | '/contenuti'
    | '/conversazioni'
    | '/dashboard'
    | '/fatturazione'
    | '/form-contatti'
    | '/gestione-pratiche'
    | '/import'
    | '/impostazioni'
    | '/liquidato'
    | '/log-registro'
    | '/magazzino'
    | '/meta-ads'
    | '/pipeline'
    | '/pratiche-perse'
    | '/preventivi-cessioni'
    | '/preventivi-prestiti'
    | '/preventivi-salvati'
    | '/privati'
    | '/prodotti'
    | '/requisiti-agente'
    | '/rinnovi'
    | '/social'
    | '/statistiche'
    | '/trattative'
    | '/clienti/$id'
    | '/lead/$id'
    | '/preventivi-salvati/$id'
    | '/clienti/'
    | '/lead/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/assicurazioni'
    | '/attivita'
    | '/automazione'
    | '/aziende'
    | '/banche'
    | '/blacklist'
    | '/calendari'
    | '/contatti'
    | '/contenuti'
    | '/conversazioni'
    | '/dashboard'
    | '/fatturazione'
    | '/form-contatti'
    | '/gestione-pratiche'
    | '/import'
    | '/impostazioni'
    | '/liquidato'
    | '/log-registro'
    | '/magazzino'
    | '/meta-ads'
    | '/pipeline'
    | '/pratiche-perse'
    | '/preventivi-cessioni'
    | '/preventivi-prestiti'
    | '/preventivi-salvati'
    | '/privati'
    | '/prodotti'
    | '/requisiti-agente'
    | '/rinnovi'
    | '/social'
    | '/statistiche'
    | '/trattative'
    | '/clienti/$id'
    | '/lead/$id'
    | '/preventivi-salvati/$id'
    | '/clienti'
    | '/lead'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/assicurazioni'
    | '/_authenticated/attivita'
    | '/_authenticated/automazione'
    | '/_authenticated/aziende'
    | '/_authenticated/banche'
    | '/_authenticated/blacklist'
    | '/_authenticated/calendari'
    | '/_authenticated/contatti'
    | '/_authenticated/contenuti'
    | '/_authenticated/conversazioni'
    | '/_authenticated/dashboard'
    | '/_authenticated/fatturazione'
    | '/_authenticated/form-contatti'
    | '/_authenticated/gestione-pratiche'
    | '/_authenticated/import'
    | '/_authenticated/impostazioni'
    | '/_authenticated/liquidato'
    | '/_authenticated/log-registro'
    | '/_authenticated/magazzino'
    | '/_authenticated/meta-ads'
    | '/_authenticated/pipeline'
    | '/_authenticated/pratiche-perse'
    | '/_authenticated/preventivi-cessioni'
    | '/_authenticated/preventivi-prestiti'
    | '/_authenticated/preventivi-salvati'
    | '/_authenticated/privati'
    | '/_authenticated/prodotti'
    | '/_authenticated/requisiti-agente'
    | '/_authenticated/rinnovi'
    | '/_authenticated/social'
    | '/_authenticated/statistiche'
    | '/_authenticated/trattative'
    | '/_authenticated/clienti/$id'
    | '/_authenticated/lead/$id'
    | '/_authenticated/preventivi-salvati_/$id'
    | '/_authenticated/clienti/'
    | '/_authenticated/lead/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trattative': {
      id: '/_authenticated/trattative'
      path: '/trattative'
      fullPath: '/trattative'
      preLoaderRoute: typeof AuthenticatedTrattativeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistiche': {
      id: '/_authenticated/statistiche'
      path: '/statistiche'
      fullPath: '/statistiche'
      preLoaderRoute: typeof AuthenticatedStatisticheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rinnovi': {
      id: '/_authenticated/rinnovi'
      path: '/rinnovi'
      fullPath: '/rinnovi'
      preLoaderRoute: typeof AuthenticatedRinnoviRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requisiti-agente': {
      id: '/_authenticated/requisiti-agente'
      path: '/requisiti-agente'
      fullPath: '/requisiti-agente'
      preLoaderRoute: typeof AuthenticatedRequisitiAgenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prodotti': {
      id: '/_authenticated/prodotti'
      path: '/prodotti'
      fullPath: '/prodotti'
      preLoaderRoute: typeof AuthenticatedProdottiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/privati': {
      id: '/_authenticated/privati'
      path: '/privati'
      fullPath: '/privati'
      preLoaderRoute: typeof AuthenticatedPrivatiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventivi-salvati': {
      id: '/_authenticated/preventivi-salvati'
      path: '/preventivi-salvati'
      fullPath: '/preventivi-salvati'
      preLoaderRoute: typeof AuthenticatedPreventiviSalvatiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventivi-prestiti': {
      id: '/_authenticated/preventivi-prestiti'
      path: '/preventivi-prestiti'
      fullPath: '/preventivi-prestiti'
      preLoaderRoute: typeof AuthenticatedPreventiviPrestitiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventivi-cessioni': {
      id: '/_authenticated/preventivi-cessioni'
      path: '/preventivi-cessioni'
      fullPath: '/preventivi-cessioni'
      preLoaderRoute: typeof AuthenticatedPreventiviCessioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pratiche-perse': {
      id: '/_authenticated/pratiche-perse'
      path: '/pratiche-perse'
      fullPath: '/pratiche-perse'
      preLoaderRoute: typeof AuthenticatedPratichePerseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meta-ads': {
      id: '/_authenticated/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof AuthenticatedMetaAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/magazzino': {
      id: '/_authenticated/magazzino'
      path: '/magazzino'
      fullPath: '/magazzino'
      preLoaderRoute: typeof AuthenticatedMagazzinoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log-registro': {
      id: '/_authenticated/log-registro'
      path: '/log-registro'
      fullPath: '/log-registro'
      preLoaderRoute: typeof AuthenticatedLogRegistroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/liquidato': {
      id: '/_authenticated/liquidato'
      path: '/liquidato'
      fullPath: '/liquidato'
      preLoaderRoute: typeof AuthenticatedLiquidatoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestione-pratiche': {
      id: '/_authenticated/gestione-pratiche'
      path: '/gestione-pratiche'
      fullPath: '/gestione-pratiche'
      preLoaderRoute: typeof AuthenticatedGestionePraticheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/form-contatti': {
      id: '/_authenticated/form-contatti'
      path: '/form-contatti'
      fullPath: '/form-contatti'
      preLoaderRoute: typeof AuthenticatedFormContattiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fatturazione': {
      id: '/_authenticated/fatturazione'
      path: '/fatturazione'
      fullPath: '/fatturazione'
      preLoaderRoute: typeof AuthenticatedFatturazioneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversazioni': {
      id: '/_authenticated/conversazioni'
      path: '/conversazioni'
      fullPath: '/conversazioni'
      preLoaderRoute: typeof AuthenticatedConversazioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contenuti': {
      id: '/_authenticated/contenuti'
      path: '/contenuti'
      fullPath: '/contenuti'
      preLoaderRoute: typeof AuthenticatedContenutiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contatti': {
      id: '/_authenticated/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof AuthenticatedContattiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendari': {
      id: '/_authenticated/calendari'
      path: '/calendari'
      fullPath: '/calendari'
      preLoaderRoute: typeof AuthenticatedCalendariRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blacklist': {
      id: '/_authenticated/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof AuthenticatedBlacklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banche': {
      id: '/_authenticated/banche'
      path: '/banche'
      fullPath: '/banche'
      preLoaderRoute: typeof AuthenticatedBancheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aziende': {
      id: '/_authenticated/aziende'
      path: '/aziende'
      fullPath: '/aziende'
      preLoaderRoute: typeof AuthenticatedAziendeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automazione': {
      id: '/_authenticated/automazione'
      path: '/automazione'
      fullPath: '/automazione'
      preLoaderRoute: typeof AuthenticatedAutomazioneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attivita': {
      id: '/_authenticated/attivita'
      path: '/attivita'
      fullPath: '/attivita'
      preLoaderRoute: typeof AuthenticatedAttivitaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assicurazioni': {
      id: '/_authenticated/assicurazioni'
      path: '/assicurazioni'
      fullPath: '/assicurazioni'
      preLoaderRoute: typeof AuthenticatedAssicurazioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lead/': {
      id: '/_authenticated/lead/'
      path: '/lead'
      fullPath: '/lead/'
      preLoaderRoute: typeof AuthenticatedLeadIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clienti/': {
      id: '/_authenticated/clienti/'
      path: '/clienti'
      fullPath: '/clienti/'
      preLoaderRoute: typeof AuthenticatedClientiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventivi-salvati_/$id': {
      id: '/_authenticated/preventivi-salvati_/$id'
      path: '/preventivi-salvati/$id'
      fullPath: '/preventivi-salvati/$id'
      preLoaderRoute: typeof AuthenticatedPreventiviSalvatiIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lead/$id': {
      id: '/_authenticated/lead/$id'
      path: '/lead/$id'
      fullPath: '/lead/$id'
      preLoaderRoute: typeof AuthenticatedLeadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clienti/$id': {
      id: '/_authenticated/clienti/$id'
      path: '/clienti/$id'
      fullPath: '/clienti/$id'
      preLoaderRoute: typeof AuthenticatedClientiIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssicurazioniRoute: typeof AuthenticatedAssicurazioniRoute
  AuthenticatedAttivitaRoute: typeof AuthenticatedAttivitaRoute
  AuthenticatedAutomazioneRoute: typeof AuthenticatedAutomazioneRoute
  AuthenticatedAziendeRoute: typeof AuthenticatedAziendeRoute
  AuthenticatedBancheRoute: typeof AuthenticatedBancheRoute
  AuthenticatedBlacklistRoute: typeof AuthenticatedBlacklistRoute
  AuthenticatedCalendariRoute: typeof AuthenticatedCalendariRoute
  AuthenticatedContattiRoute: typeof AuthenticatedContattiRoute
  AuthenticatedContenutiRoute: typeof AuthenticatedContenutiRoute
  AuthenticatedConversazioniRoute: typeof AuthenticatedConversazioniRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFatturazioneRoute: typeof AuthenticatedFatturazioneRoute
  AuthenticatedFormContattiRoute: typeof AuthenticatedFormContattiRoute
  AuthenticatedGestionePraticheRoute: typeof AuthenticatedGestionePraticheRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedLiquidatoRoute: typeof AuthenticatedLiquidatoRoute
  AuthenticatedLogRegistroRoute: typeof AuthenticatedLogRegistroRoute
  AuthenticatedMagazzinoRoute: typeof AuthenticatedMagazzinoRoute
  AuthenticatedMetaAdsRoute: typeof AuthenticatedMetaAdsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPratichePerseRoute: typeof AuthenticatedPratichePerseRoute
  AuthenticatedPreventiviCessioniRoute: typeof AuthenticatedPreventiviCessioniRoute
  AuthenticatedPreventiviPrestitiRoute: typeof AuthenticatedPreventiviPrestitiRoute
  AuthenticatedPreventiviSalvatiRoute: typeof AuthenticatedPreventiviSalvatiRoute
  AuthenticatedPrivatiRoute: typeof AuthenticatedPrivatiRoute
  AuthenticatedProdottiRoute: typeof AuthenticatedProdottiRoute
  AuthenticatedRequisitiAgenteRoute: typeof AuthenticatedRequisitiAgenteRoute
  AuthenticatedRinnoviRoute: typeof AuthenticatedRinnoviRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedStatisticheRoute: typeof AuthenticatedStatisticheRoute
  AuthenticatedTrattativeRoute: typeof AuthenticatedTrattativeRoute
  AuthenticatedClientiIdRoute: typeof AuthenticatedClientiIdRoute
  AuthenticatedLeadIdRoute: typeof AuthenticatedLeadIdRoute
  AuthenticatedPreventiviSalvatiIdRoute: typeof AuthenticatedPreventiviSalvatiIdRoute
  AuthenticatedClientiIndexRoute: typeof AuthenticatedClientiIndexRoute
  AuthenticatedLeadIndexRoute: typeof AuthenticatedLeadIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssicurazioniRoute: AuthenticatedAssicurazioniRoute,
  AuthenticatedAttivitaRoute: AuthenticatedAttivitaRoute,
  AuthenticatedAutomazioneRoute: AuthenticatedAutomazioneRoute,
  AuthenticatedAziendeRoute: AuthenticatedAziendeRoute,
  AuthenticatedBancheRoute: AuthenticatedBancheRoute,
  AuthenticatedBlacklistRoute: AuthenticatedBlacklistRoute,
  AuthenticatedCalendariRoute: AuthenticatedCalendariRoute,
  AuthenticatedContattiRoute: AuthenticatedContattiRoute,
  AuthenticatedContenutiRoute: AuthenticatedContenutiRoute,
  AuthenticatedConversazioniRoute: AuthenticatedConversazioniRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFatturazioneRoute: AuthenticatedFatturazioneRoute,
  AuthenticatedFormContattiRoute: AuthenticatedFormContattiRoute,
  AuthenticatedGestionePraticheRoute: AuthenticatedGestionePraticheRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedLiquidatoRoute: AuthenticatedLiquidatoRoute,
  AuthenticatedLogRegistroRoute: AuthenticatedLogRegistroRoute,
  AuthenticatedMagazzinoRoute: AuthenticatedMagazzinoRoute,
  AuthenticatedMetaAdsRoute: AuthenticatedMetaAdsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPratichePerseRoute: AuthenticatedPratichePerseRoute,
  AuthenticatedPreventiviCessioniRoute: AuthenticatedPreventiviCessioniRoute,
  AuthenticatedPreventiviPrestitiRoute: AuthenticatedPreventiviPrestitiRoute,
  AuthenticatedPreventiviSalvatiRoute: AuthenticatedPreventiviSalvatiRoute,
  AuthenticatedPrivatiRoute: AuthenticatedPrivatiRoute,
  AuthenticatedProdottiRoute: AuthenticatedProdottiRoute,
  AuthenticatedRequisitiAgenteRoute: AuthenticatedRequisitiAgenteRoute,
  AuthenticatedRinnoviRoute: AuthenticatedRinnoviRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedStatisticheRoute: AuthenticatedStatisticheRoute,
  AuthenticatedTrattativeRoute: AuthenticatedTrattativeRoute,
  AuthenticatedClientiIdRoute: AuthenticatedClientiIdRoute,
  AuthenticatedLeadIdRoute: AuthenticatedLeadIdRoute,
  AuthenticatedPreventiviSalvatiIdRoute: AuthenticatedPreventiviSalvatiIdRoute,
  AuthenticatedClientiIndexRoute: AuthenticatedClientiIndexRoute,
  AuthenticatedLeadIndexRoute: AuthenticatedLeadIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
